services:
  verdaccio:
    image: verdaccio/verdaccio:local
    container_name: verdaccio
    networks:
      - 1panel-network
    environment:
      - VERDACCIO_PORT=40087
    ports:
      - 40087:40087
    volumes:
      - ./data/storage:/verdaccio/storage
      - ./data/config:/verdaccio/conf
      - ./data/plugins:/verdaccio/plugins
    labels:
      createdBy: 'Apps'
networks:
  1panel-network:
    external: true
